name: Terraform file formatting

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    name: file format checker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: my-terraform-config

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with: 
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update terraform files to canonical format using 'terraform fmt'
          branch: automated-terraform-fmt